const actionTypes = {
    ADD_TASK: 'ADD-TASK',
    MOVE_TASK_TO_WORK: 'MOVE-TASK-TO-WORK',
    MOVE_TASK_TO_ORDER: 'MOVE-TASK-TO-ORDER',
    MOVE_TASK_TO_INSPECTION: 'MOVE-TASK-TO-INSPECTION',
    MOVE_TASK_TO_COMPLETE: 'MOVE-TASK-TO-COMPLETE',
};

export default actionTypes;